# Generated by Django 3.1.2 on 2021-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('cover', models.CharField(blank=True, max_length=300, null=True)),
                ('describe', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
